# Generated by Django 2.2.4 on 2019-08-31 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('content', models.TextField(verbose_name='Mensagem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Chat Publico',
                'verbose_name_plural': 'Chats Publicos',
            },
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='msgprivadas',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.DeleteModel(
            name='PublicChat',
        ),
    ]
