# Generated by Django 2.2.3 on 2019-08-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190830_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('idPrivado', 'idPublico', 'email')},
        ),
    ]
