# Generated by Django 2.2.3 on 2019-08-31 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('chat', '0003_auto_20190830_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatPublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgpublica', models.TextField(verbose_name='Mensagens')),
                ('userpublic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idla', to='core.usuario', verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Chat Publico',
                'verbose_name_plural': 'Chats Publicos',
            },
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
