# Generated by Django 2.2.3 on 2019-08-31 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('chat', '0004_auto_20190831_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatpublico',
            name='userpublic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idsocial', to='core.usuario', verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='chatPrivado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgprivadas', models.TextField(verbose_name='Mensagens')),
                ('usersecret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idsecret', to='core.usuario', verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Chat Privado',
                'verbose_name_plural': 'Chats Privados',
            },
        ),
    ]
